"""Repository interface and factory for user-service.

Defines the UserRepository abstract base class and the get_repository()
factory that selects the concrete implementation based on STORAGE_BACKEND.

REQ-USR-09: configuration drives backend selection.
REQ-USR-B01: email uniqueness enforced atomically in each backend.
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from pathlib import Path
from typing import Any


class UserRepository(ABC):
    """Abstract interface for user storage backends.

    All methods work with plain dict records containing the eight User fields:
        id, first_name, last_name, email, company, role, created_at, updated_at

    Implementations MUST return copies of stored records, never references.
    Email uniqueness is verified atomically with the write operation.
    """

    @abstractmethod
    def create(self, user: dict[str, Any]) -> dict[str, Any]:
        """Persist a new user record.

        Parameters
        ----------
        user:
            Complete user dict including all eight fields (id and timestamps
            already generated by the service layer).

        Returns
        -------
        Copy of the stored record.

        Raises
        ------
        EmailAlreadyExists
            If another user with the same normalised email already exists.
        """

    @abstractmethod
    def get(self, user_id: str) -> dict[str, Any] | None:
        """Return the user with the given id, or None if not found."""

    @abstractmethod
    def get_by_email(self, email: str) -> dict[str, Any] | None:
        """Return the user whose normalised email matches *email*, or None."""

    @abstractmethod
    def list(
        self,
        filters: dict[str, Any],
        page: int,
        page_size: int,
    ) -> tuple[list[dict[str, Any]], int]:
        """Return a paginated, filtered list of users.

        Parameters
        ----------
        filters:
            Dict with optional keys ``role`` and/or ``email`` (already
            normalised to lowercase by the service layer).
        page:
            1-based page number.
        page_size:
            Maximum number of items per page.

        Returns
        -------
        (items, total) where *total* is the count of all matching records
        before pagination and *items* is at most *page_size* copies.
        The ordering is (created_at, id) ascending, stable across backends.
        A page beyond the end returns an empty list (not an error).
        """

    @abstractmethod
    def update(self, user_id: str, user: dict[str, Any]) -> dict[str, Any] | None:
        """Replace the stored record for *user_id* with *user*.

        Parameters
        ----------
        user_id:
            Identifier of the record to update.
        user:
            Complete updated dict. The id and email fields are already set by
            the service layer.

        Returns
        -------
        Copy of the updated record, or None if no record with *user_id* exists.

        Raises
        ------
        EmailAlreadyExists
            If *user*'s email belongs to a *different* user. The existing
            record must remain unchanged in this case.
        """

    @abstractmethod
    def delete(self, user_id: str) -> bool:
        """Remove the user with *user_id*.

        Returns
        -------
        True if the record existed and was removed, False otherwise.
        """


def get_repository(backend: str, data_dir: Path) -> UserRepository:
    """Factory: return the UserRepository implementation for *backend*.

    Parameters
    ----------
    backend:
        One of ``memory``, ``json``, ``sqlite``.
    data_dir:
        Directory used by the file-based backends (ignored for memory).

    Raises
    ------
    ValueError
        If *backend* is not a recognised backend name.
    """
    if backend == "memory":
        from app.repositories.memory import MemoryRepository
        return MemoryRepository()
    if backend == "json":
        from app.repositories.json_repo import JsonRepository
        return JsonRepository(data_dir)
    if backend == "sqlite":
        from app.repositories.sqlite_repo import SqliteRepository
        return SqliteRepository(data_dir)
    raise ValueError(f"Unknown storage backend: {backend!r}")
